project:
  type: website
  output-dir: .

website:
  title: "ABS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Help
        menu:
        - r-help.qmd
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



